Added Settlement toCsv
payfunc/model-acquirer pull request #102
Opened 2021-05-24 14:39 UTC by florianebmeier

2021-05-24 14:46 UTC, robinnedergard requested changes

2021-05-24 14:46 UTC, robinnedergard commented on Settlement/index.ts
> +
Don't need the space

2021-05-24 14:46 UTC, robinnedergard commented on Settlement/index.ts
> +			}","${settlement.payout}","${settlement.net - (settlement.reserve?.amount ?? 0)}","${
We want to round all the outgoing values from arithmetic operations

2021-05-24 14:53 UTC, robinnedergard approved these changes

2021-05-25 08:50 UTC, fredrikbryntesson approved these changes

2021-05-25 08:50 UTC, merged