Detailed tocsv
payfunc/model-acquirer pull request #109
Opened 2021-05-26 12:14 UTC by marcushanses

2021-05-26 12:19 UTC, florianebmeier requested changes

2021-05-26 12:19 UTC, florianebmeier commented on Settlement/Conversion.ts
> +		let result =
Rewrite into the same structure as toDetailedCsv

2021-05-26 14:42 UTC, florianebmeier submitted a review, later dismissed

2021-05-26 14:43 UTC, nilssonemma submitted a review, later dismissed

2021-05-26 15:40 UTC, Magnus93 submitted a review, later dismissed

2021-05-28 08:07 UTC, fredrikbryntesson submitted a review, later dismissed

2021-05-28 08:47 UTC, fredrikbryntesson approved these changes

2021-05-28 08:57 UTC, merged