Provide 3dVersion through Verification Creatable
payfunc/model-acquirer pull request #116
Opened 2021-05-31 08:50 UTC by florianebmeier

2021-05-31 08:51 UTC, robinnedergard approved these changes

2021-05-31 08:51 UTC, robinnedergard requested changes
forgot version typecheck

2021-05-31 08:57 UTC, robinnedergard approved these changes

2021-06-01 09:47 UTC, fredrikbryntesson approved these changes

2021-06-01 09:47 UTC, merged