Bumped model-card.
payfunc/model-acquirer pull request #145
Opened 2021-06-22 09:01 UTC by marcushanses

2021-06-22 11:20 UTC, florianebmeier approved these changes

2021-06-22 13:06 UTC, robinnedergard requested changes

2021-06-22 13:06 UTC, robinnedergard commented on Authorization/History/Verification.ts
> +	customer?: base.Contact
`//@depracated` missing?

2021-06-22 22:11 UTC, robinnedergard approved these changes

2021-06-23 06:31 UTC, fredrikbryntesson approved these changes

2021-06-23 06:31 UTC, merged