Silverflow model changes
payfunc/model-acquirer pull request #163
Opened 2021-08-30 15:18 UTC by Magnus93

2021-08-30 15:44 UTC, robinnedergard requested changes

2021-08-30 15:44 UTC, robinnedergard commented on Merchant/Acceptor.ts
> +			typeof value == "object" &&
Change line to `typeof value == "object" && value &&` to avoid crashing if value is null.

2021-08-30 15:44 UTC, robinnedergard commented on Merchant/Acceptor.ts
> +			typeof value == "object" &&
Repeat for all `typeof value == "object"`. ~Thank the programming gods for javascript null objects!~

2021-08-31 14:45 UTC, marcushanses approved these changes

2021-08-31 15:09 UTC, nilssonemma approved these changes

2021-09-01 08:29 UTC, robinnedergard approved these changes

2021-09-02 22:17 UTC, fredrikbryntesson approved these changes

2021-09-02 22:17 UTC, merged