Support for listing authorizations as states
payfunc/model-acquirer pull request #169
Opened 2021-09-07 11:27 UTC by nilssonemma

2021-09-08 07:20 UTC, robinnedergard requested changes

2021-09-08 07:20 UTC, robinnedergard commented on Client/Authorization.ts
> +		const query = !state ? (date ? "?" + date : "") : "?state=true" + (date ? "&" + date : "")
Make all query parameters optional and not dependent on one another

2021-09-08 09:21 UTC, robinnedergard approved these changes

2021-09-08 13:43 UTC, robinnedergard submitted a review, later dismissed

2021-09-09 06:56 UTC, Magnus93 submitted a review, later dismissed

2021-09-09 07:46 UTC, robinnedergard approved these changes

2021-09-09 12:36 UTC, fredrikbryntesson approved these changes

2021-09-09 12:37 UTC, merged