Statistics
payfunc/model-acquirer pull request #24
Opened 2021-02-23 15:58 UTC by nilssonemma

2021-02-23 16:34 UTC, florianebmeier requested changes

2021-02-23 16:34 UTC, florianebmeier commented on Statistics.ts
> +			authly.Identifier.is(value.merchant) &&
Put the length of 8 in the authly Identifier typeguard

2021-02-23 16:34 UTC, florianebmeier commented on Statistics.ts
> +	export function sum(record: Record<isoly.Date, number>, days?: number): number {
`from?:isoly.Date | number, to?:isoly.Date`

2021-02-24 08:21 UTC, florianebmeier approved these changes

2021-02-24 09:16 UTC, fredrikbryntesson approved these changes

2021-02-24 09:16 UTC, merged