Extended CSV file.
payfunc/model-acquirer pull request #36
Opened 2021-03-11 15:08 UTC by nilssonemma

2021-03-11 15:12 UTC, robinnedergard requested changes

2021-03-11 15:12 UTC, robinnedergard commented on Settlement/index.spec.ts
> +	const merchant: Merchant = {
Use testtest merchant for testdata

2021-03-11 15:18 UTC, robinnedergard approved these changes

2021-03-11 15:21 UTC, robinnedergard requested changes
Change other toCsv

2021-03-11 15:37 UTC, robinnedergard submitted a review, later dismissed

2021-03-12 10:00 UTC, florianebmeier approved these changes

2021-03-12 10:08 UTC, robinnedergard approved these changes

2021-03-12 10:17 UTC, florianebmeier approved these changes

2021-03-12 15:12 UTC, fredrikbryntesson approved these changes

2021-03-12 15:12 UTC, merged