toCsv implemented for authorizations
payfunc/model-acquirer pull request #62
Opened 2021-04-14 11:28 UTC by robinnedergard

2021-04-14 11:35 UTC, florianebmeier requested changes

2021-04-14 11:35 UTC, florianebmeier commented on Authorization/index.spec.ts
> +				`"123456789023456","testtest","undefined","12341234","2021-04-01T09:00:00.000Z","101.1","SEK","debit","visa","123456** **** ****1111","02/2028","undefined","false","0","0","0","not voided","autho
We never want to write undefined as a string into here. It should just be an empty field `,,`

2021-04-14 11:35 UTC, florianebmeier commented on Authorization/index.ts
> +			result += Change.toCsv(value.history)
I dont understand what the point of this is. why would we append a second table to the first one. Think about how that would look in an excel file

2021-04-14 11:35 UTC, florianebmeier commented on Authorization/Change/index.ts
> +	export function toCsv(history: Change[]): string {
I dont think we need to have toCsv for the change / capture / refund parts.

2021-04-15 07:53 UTC, florianebmeier approved these changes

2021-04-15 09:32 UTC, nilssonemma approved these changes

2021-04-15 14:03 UTC, fredrikbryntesson approved these changes

2021-04-15 14:03 UTC, merged