Authorization state changes
payfunc/model-acquirer pull request #64
Opened 2021-04-15 07:11 UTC by florianebmeier

2021-04-15 12:21 UTC, nilssonemma requested changes

2021-04-15 12:21 UTC, nilssonemma commented on State/Authorization.ts
> +	authorization: {
Add status and history.

2021-04-15 12:21 UTC, nilssonemma commented on State/Authorization.ts
> +		captured?: { amount: number; latest: isoly.DateTime; auto?: true }
change type of captured to Capture[] and refunded to Refund[]

2021-04-16 07:44 UTC, nilssonemma approved these changes

2021-04-16 07:47 UTC, nilssonemma requested changes

2021-04-16 07:47 UTC, nilssonemma commented on State/Authorization.ts
> +	export function is(value: any | Authorization): value is Authorization {
Update typeguard with the new changes

2021-04-16 14:33 UTC, nilssonemma approved these changes

2021-04-16 20:49 UTC, fredrikbryntesson approved these changes

2021-04-16 20:49 UTC, merged