Simple verification logging
payfunc/model-acquirer pull request #67
Opened 2021-04-21 10:32 UTC by florianebmeier

2021-04-21 11:06 UTC, robinnedergard requested changes

2021-04-21 11:06 UTC, robinnedergard commented on State/FailedAuthorization.ts
> +
Unnecessary curly brackets and empty line

2021-04-21 11:10 UTC, robinnedergard approved these changes

2021-04-22 12:50 UTC, fredrikbryntesson approved these changes

2021-04-22 12:50 UTC, merged