Added scheme fee to settlement
payfunc/model-acquirer pull request #70
Opened 2021-04-26 13:55 UTC by nilssonemma

2021-04-26 14:23 UTC, florianebmeier requested changes

2021-04-26 14:23 UTC, florianebmeier commented on Settlement/Transaction.ts
> +			(typeof value.fee == "number" || (typeof value.fee.scheme == "number" && typeof value.fee.total == "number")) &&
Isnt this missing the typeof value.fee == "object" check?

2021-04-26 14:23 UTC, florianebmeier commented on Settlement/index.ts
> +			(typeof value.fee == "number" || (typeof value.fee.scheme == "number" && typeof value.fee.total)) &&
See above

2021-04-26 14:23 UTC, florianebmeier commented on Settlement/index.ts
> +	export function toCustomer(settlements: Settlement[]): Settlement[] {
i think we want the function to be on the settlement itself so if we have a use case where we only return a single settlement, we can still use the .toCustomer function

2021-04-26 14:23 UTC, florianebmeier commented on Settlement/index.ts
> +	export function toCustomer(settlements: Settlement[]): Settlement[] {
Also this is missing that you have to use .toCustomer function on all of the transactions in the transactions field

2021-04-26 14:23 UTC, florianebmeier commented on Settlement/Transaction.ts
> +	export function toCustomer(transactions: Transaction[]): Transaction[] {
Should also be possible for a single transaction, not only for an array.

2021-04-26 14:56 UTC, florianebmeier submitted a review, later dismissed

2021-04-26 14:59 UTC, robinnedergard submitted a review, later dismissed

2021-04-27 07:21 UTC, robinnedergard approved these changes

2021-04-27 07:38 UTC, florianebmeier approved these changes

2021-04-27 09:21 UTC, fredrikbryntesson approved these changes

2021-04-27 09:21 UTC, merged