Sprint 21.09 changes
payfunc/model-acquirer pull request #86
Opened 2021-05-12 08:27 UTC by Magnus93

Pares moved from common-worker to this branch
Verification interface added
`Merchant.reconciliation.currency` moved to `Merchant.currency`
Uses repo `model-base` for `Browser`, `Item` and `Customer`

2021-05-12 09:19 UTC, robinnedergard requested changes

2021-05-12 09:19 UTC, robinnedergard commented on Authorization/Creatable.ts
> +			typeof value.number == "string" &&
As a corresponding change: 
In the flaw function further down (line 35 & 36) change from:
`value.number == undefined ||
								typeof value.number == "string" || { property: "number", type: "string | undefined" },`
into
`typeof value.number == "string" || { property: "number", type: "string" },`

2021-05-12 09:19 UTC, robinnedergard commented on Merchant/Reconciliation/index.ts
> +					Object.values(value.account).every(account => isoly.Currency.is(account)))) &&
1. Do Object.entries instead and combine into one row.
2. Second type check (for values) is incorrect, should be `Account.is` and not `isoly.Currency.is`

2021-05-12 09:19 UTC, robinnedergard commented on Settlement/Transaction.ts
>  		let result = "authorization,reference,type,card,scheme,area,created,gross,fee,net,reserve amount,reserve payout\r\n"
Insert currency header (between created and gross)

2021-05-12 09:19 UTC, robinnedergard commented on Settlement/Transaction.ts
> +			}","${value.created}","${value.gross}","${value.currency}","${
Move currency between created and gross

2021-05-12 09:19 UTC, robinnedergard commented on Settlement/index.spec.ts
> +				'"12345","234242","authorization","debit","mastercard","SE","2020-02-16","2","SEK","3","12","undefined","undefined"\r\n'
Move currency between created and gross (switch place of "2" and "SEK")

2021-05-12 09:19 UTC, robinnedergard commented on Settlement/index.spec.ts
>  			"reference,merchant,start date,end date,payout date,reserve amount,reserve payout,created,gross,fee,net,currency\r\n" +
Output will contain currency header (between created and gross) when corresponding changes are made

2021-05-12 09:19 UTC, robinnedergard commented on State/PreAuthorization.spec.ts
> +			{ EUR: 10, SEK: 0.1 }
Double check that the tests are correct, some currency that was removed was "USD" while merchant contained "SEK", this is in several tests. Harder fix, so maybe leave for last.

2021-05-12 09:19 UTC, robinnedergard commented on Verification/Creatable.ts
> +			(["initial", "subsequent"].includes(value.recurring) && value.customer == undefined) ||
Something wrong with parenthesis, should for example be:
`(value.recurring == undefined || ["initial", "subsequent"].includes(value.recurring))`

2021-05-12 09:19 UTC, robinnedergard commented on Verification/Creatable.ts
> +			base.Customer.is(value.customer)
`(value.customer == undefined || base.Customer.is(value.customer))`

2021-05-12 13:00 UTC, Magnus93 commented on State/PreAuthorization.spec.ts
> +			{ EUR: 10, SEK: 0.1 }
Tests are correct. Only `EUR` and `SEK` are used

2021-05-12 13:25 UTC, Magnus93 commented on Settlement/index.spec.ts
>  			"reference,merchant,start date,end date,payout date,reserve amount,reserve payout,created,gross,fee,net,currency\r\n" +
Nope, the changes does not affect `Settlement.currency` in `toCsv` 
It only affects `Transaction.currency`

2021-05-12 15:18 UTC, robinnedergard approved these changes

2021-05-17 06:52 UTC, nilssonemma requested changes

2021-05-17 06:52 UTC, nilssonemma commented on Merchant/Reconciliation/index.ts
>  			Fee.is(value.fees) &&
Add costPlus to typeguard

2021-05-17 06:52 UTC, nilssonemma commented on Merchant/Reconciliation/index.ts
> +				Object.entries(value.account).every(
The key can also be undefined

2021-05-17 06:52 UTC, nilssonemma commented on Merchant/Reconciliation/index.ts
>  			Fee.is(value.fees) &&
Also update flaw function

2021-05-17 06:52 UTC, nilssonemma commented on Merchant/index.ts
> +	currency: isoly.Currency
Update typeguard and flaw function

2021-05-17 06:52 UTC, nilssonemma commented on Merchant/Reconciliation/index.ts
> +				Object.entries(value.account).every(
The line (typeof value.account == "object" && Account.is(value.account)) can be removed since the line above does the same check

2021-05-18 06:22 UTC, nilssonemma approved these changes

2021-05-18 09:03 UTC, florianebmeier requested changes

2021-05-18 09:03 UTC, florianebmeier commented on package.json
> +		"@payfunc/model-base": "github:payfunc/model-base",
Get model-base from npm version

2021-05-18 11:55 UTC, robinnedergard approved these changes

2021-05-18 12:45 UTC, florianebmeier approved these changes

2021-05-18 13:10 UTC, nilssonemma approved these changes

2021-05-19 10:55 UTC, merged